language: python

# see https://docs.travis-ci.com/user/multi-os/
matrix:
  include:
    - os: linux
      sudo: required
      python: 3.4
    - os: osx
      language: generic
#  allow_failures:
#    - os: osx

install:
  - if [ "$TRAVIS_OS_NAME" == "osx"   ] ; then   mac-build/build.sh ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then linux-build/build.sh ; fi

script:
  - if [ "$TRAVIS_OS_NAME" == "osx"   ] ; then   mac-build/test.sh ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then linux-build/test.sh ; fi

after_script:
  # https://github.com/codeclimate/python-test-reporter
  # set the environment variable CODECLIMATE_REPO_TOKEN in travis-ci settings
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then codeclimate-test-reporter ; fi

before_deploy:
  # create the documentation
  - if [ "$TRAVIS_OS_NAME" == "linux" ] ; then ( cd docs ; make html ; ) ; fi

deploy:
  # created with travis command line tool
  # https://docs.travis-ci.com/user/deployment/pypi
  # $ travis setup pypi
  provider: pypi
  user: niccokunzmann2
  password:
    secure: "q3aUT6A5Mvkdg4JPZQGYQSLi7i0Kk3/raebav1gVC0CZBEPMOBRbuL1ZgpHV7wM4emqr1p2mTl3R4YjCn8Kn1J7zWtmWUBnMystbW8ojQ4ED3qk+zHnI85Zk/TE5N4KlRN0iAGFPeFZpgXTr6gpiFmLkgvaGhAKg4HWMOOIZ9FENz/XtJU5XxCjLuBykIy+YeoVDaJPyX05rfrUxN5GfxEhBiEjpF2UL1M6fYv+3Orn4AgQpZu0DGTItARXanE8J9L1vqU17tGmBwLmXyklbG/7lwd/c295COxHgEQbcZeOl/Dbu9SE8nvBtZd3TiR9K05BVWgQAheClf980ncjI9eCJsmJC3s3XMucTTWTuZEucenfvGTE0h6mKEEvgEMREfr9LJR2+teT7vlocUWpscLJEdTShJvt1BtUVeOXLdIEjTvPNmU0ItZ5qipoaWrsH0q9l85c02cLK/yqkN11hn9WnLH7AWpRoj51W4sXjcfKX341MJqqHaXGcPrufkNP6g0SaGdqA0kkK7iMA+SYCeUI+K9UzJbmlgVbiIm/blVqK1eKcuB652/apPXi72EDVXhg9Q5LphGfNtlZ09iPEZYKTo0NsCZ+AXcoyoPE7Y+zqsky33lZcaRxPnY1Ba2f9/1MTU+uK6FlHuhi/N+y55HVCCG41jaMUNq5BcXeFHo4="
  on:
    tags: true
    distributions: sdist bdist_wininst bdist_wheel
    repo: AllYarnsAreBeautiful/kniteditor

