url: https://fossasia.github.io
# set this to "" if in development mode
base-url: /kniteditor
permalink: /blog/:year-:month-:day/:title
sourcecode:
  repository: "https://github.com/fossasia/kniteditor"
  root: "https://github.com/fossasia/kniteditor/tree/gh-pages"
languages:
  - en
  - de