url: https://fossasia.github.io/kniteditor
permalink: /blog/:year-:month-:day/:title
sourcecode:
  repository: "https://github.com/fossasia/kniteditor"
  root: "https://github.com/fossasia/kniteditor/tree/gh-pages"
